version: "3.9"
name: TaskManagement
services:
  app:
    container_name: app_container
    image: app-image
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - APP_ENV=docker
    depends_on:
      - redis
    ports:
      - "5005:5005"
    expose:
      - "5005"
    volumes:
      - ./src:/usr/src/app
    networks:
      - app_network
    restart: unless-stopped
  postgres:
    container_name: postgres_container
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_management
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis:


networks:
  app_network:
    driver: bridge