version: "3.9"
name: task_management
services:
  app:
    container_name: app_container
    image: app-image
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      - APP_ENV=docker
    depends_on:
      - postgres
    ports:
      - "5005:5005"
    expose:
      - "5005"
    volumes:
      - ./src:/usr/src/app
    networks:
      - app_network
    restart: unless-stopped
  postgres:
    image: postgres:16.2
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_management
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - app_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8090:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - app_network
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:


networks:
  app_network:
    driver: bridge